language: node_js
node_js:
- '6.10'
notifications:
  slack:
    secure: g6eiX6ALpd0VvGsSCDyCGpwtkvTT3qDcNTwXFK7yj85y4ZaRPUHqV22RXUn+7hyvPDbaXM1o61Q5EwBCC3XGlzirqGoM0l22TDQq3ZchtJGTSFrALcWGHaj6YHCQOyHu4TbFsaYGzMNG0o2DVjC2A1L/psoLVj5S0mQXtRmsWNiBAfff4kqOBYk76459rCkAGoUkV5Wwz6D0XPdLxVFmOqtfFdt427jjZcQp9tj5as9B33ERm4kdIKX2/CXdJE3F7+YjKeyrUhrqggLRJiTBKc53reoy8X26QjExfQ95ewPkdHx+CAnXKhW1TLym4+EpRTSrQIFt2dhKvT+0VU4X3XIKlxTn2KA/UX/1Qln6s8SMRqzeaNqB6t8rckzqQ3NN5HSgHmcERnmwFaRM4mPfxwTf5RR0bnoZd4iq7x3hiznztLJp3S5i1hUQCm8IJ83sTEU9LHsVdaaBjTOk7FAtATGX3IGA86BKVvdpULgQFaucAx5jRXIGyRFqcuzka3B4UYSyfatU3i+KRVDIuo+PkbcsjLL7EGT3fPZVeXgXnxdLQT7s9mKtEMhCDGOzH4gApJJn62Z+x0m3hoUgR8Y5sw9o9yoiwD2ldlQtYQ/1iMP/mku3gyF8nsCe9AR3nMmUJGyCufEBOTR8A6THscINRU/4pVxWfdFDAUjz1qoADKM=
